export const menuData = {
  en: {
    starters: {
      title: "Starters",
      items: [
        {
          name: "Chicken Tartare",
          description: "Hand-cut prime chicken, quail egg yolk, truffle oil, crispy capers, sourdough",
          price: "18",
          allergens: "Gluten, Eggs",
          rating: 4.8,
        },
        {
          name: "Burrata & Heritage Tomatoes",
          description: "Creamy burrata, heirloom tomatoes, basil oil, aged balsamic, pine nuts",
          price: "16",
          allergens: "Dairy, Nuts",
          rating: 4.9,
        },
        {
          name: "Smoked Salmon Roulade",
          description: "House-smoked salmon, horseradish cream, cucumber, dill, pumpernickel",
          price: "17",
          allergens: "Fish, Gluten, Dairy",
          rating: 4.7,
        },
        {
          name: "Wild Mushroom Soup",
          description: "Seasonal forest mushrooms, truffle foam, chive oil, crispy shallots",
          price: "14",
          allergens: "Dairy",
          rating: 4.6,
        },
      ],
    },
    mains: {
      title: "Main Courses",
      items: [
        {
          name: "Wiener Schnitzel",
          description: "Traditional veal schnitzel, potato salad, lingonberries, lemon",
          price: "32",
          allergens: "Gluten, Eggs",
          rating: 4.9,
        },
        {
          name: "Chicken Rouladen",
          description: "Braised Chicken rolls, bacon, pickles, mustard, red cabbage, spätzle",
          price: "34",
          allergens: "Gluten, Dairy",
          rating: 4.8,
        },
        {
          name: "Pan-Seared Sea Bass",
          description: "Mediterranean sea bass, fennel purée, saffron broth, samphire",
          price: "36",
          allergens: "Fish",
          rating: 4.9,
        },
        {
          name: "Wild Boar Medallions",
          description: "Herb-crusted wild boar, cranberry reduction, root vegetables, potato gratin",
          price: "38",
          allergens: "Dairy, Nuts",
          rating: 4.7,
        },
        {
          name: "Truffle Risotto",
          description: "Carnaroli rice, black truffle, parmesan, white wine, butter",
          price: "28",
          allergens: "Dairy, Alcohol",
          rating: 4.8,
        },
        {
          name: "Duck Confit",
          description: "Slow-cooked duck leg, orange glaze, Brussels sprouts, potato rösti",
          price: "35",
          allergens: "Dairy",
          rating: 4.9,
        },
      ],
    },
    desserts: {
      title: "Desserts",
      items: [
        {
          name: "Black Forest Gâteau",
          description: "Chocolate sponge, kirsch-soaked cherries, vanilla cream, chocolate shavings",
          price: "12",
          allergens: "Gluten, Eggs, Dairy, Alcohol",
          rating: 4.9,
        },
        {
          name: "Apple Strudel",
          description: "Traditional apple strudel, vanilla sauce, cinnamon ice cream",
          price: "11",
          allergens: "Gluten, Dairy, Nuts",
          rating: 4.8,
        },
        {
          name: "Crème Brûlée",
          description: "Madagascar vanilla bean, caramelized sugar, seasonal berries",
          price: "10",
          allergens: "Eggs, Dairy",
          rating: 4.7,
        },
        {
          name: "Chocolate Fondant",
          description: "Molten dark chocolate cake, salted caramel, pistachio ice cream",
          price: "13",
          allergens: "Gluten, Eggs, Dairy, Nuts",
          rating: 5.0,
        },
      ],
    },
  },
  de: {
    starters: {
      title: "Vorspeisen",
      items: [
        {
          name: "Rindertatar",
          description: "Handgeschnittenes Rinderfilet, Wachtelei, Trüffelöl, knusprige Kapern, Sauerteigbrot",
          price: "18",
          allergens: "Gluten, Eier",
          rating: 4.8,
        },
        {
          name: "Burrata & Erbstück-Tomaten",
          description: "Cremige Burrata, Erbstück-Tomaten, Basilikumöl, gereifter Balsamico, Pinienkerne",
          price: "16",
          allergens: "Milchprodukte, Nüsse",
          rating: 4.9,
        },
        {
          name: "Geräucherte Lachs-Roulade",
          description: "Hausgeräucherter Lachs, Meerrettichcreme, Gurke, Dill, Pumpernickel",
          price: "17",
          allergens: "Fisch, Gluten, Milchprodukte",
          rating: 4.7,
        },
        {
          name: "Waldpilzsuppe",
          description: "Saisonale Waldpilze, Trüffelschaum, Schnittlauchöl, knusprige Schalotten",
          price: "14",
          allergens: "Milchprodukte",
          rating: 4.6,
        },
      ],
    },
    mains: {
      title: "Hauptgerichte",
      items: [
        {
          name: "Wiener Schnitzel",
          description: "Traditionelles Kalbsschnitzel, Kartoffelsalat, Preiselbeeren, Zitrone",
          price: "32",
          allergens: "Gluten, Eier",
          rating: 4.9,
        },
        {
          name: "Rinderrouladen",
          description: "Geschmorte Rinderrouladen, Speck, Gurken, Senf, Rotkohl, Spätzle",
          price: "34",
          allergens: "Gluten, Milchprodukte",
          rating: 4.8,
        },
        {
          name: "Gebratener Wolfsbarsch",
          description: "Mediterrane Wolfsbarsch, Fenchelpüree, Safranbrühe, Meeresspargel",
          price: "36",
          allergens: "Fisch",
          rating: 4.9,
        },
        {
          name: "Wildschwein-Medaillons",
          description: "Kräuterkruste Wildschwein, Preiselbeersauce, Wurzelgemüse, Kartoffelgratin",
          price: "38",
          allergens: "Milchprodukte, Nüsse",
          rating: 4.7,
        },
        {
          name: "Trüffel-Risotto",
          description: "Carnaroli-Reis, schwarze Trüffel, Parmesan, Weißwein, Butter",
          price: "28",
          allergens: "Milchprodukte, Alkohol",
          rating: 4.8,
        },
        {
          name: "Entenconfit",
          description: "Langsam gegarte Entenkeule, Orangenglasur, Rosenkohl, Kartoffelrösti",
          price: "35",
          allergens: "Milchprodukte",
          rating: 4.9,
        },
      ],
    },
    desserts: {
      title: "Desserts",
      items: [
        {
          name: "Schwarzwälder Kirschtorte",
          description: "Schokoladenbiskuit, Kirsch-getränkte Kirschen, Vanillecreme, Schokoladenraspeln",
          price: "12",
          allergens: "Gluten, Eier, Milchprodukte, Alkohol",
          rating: 4.9,
        },
        {
          name: "Apfelstrudel",
          description: "Traditioneller Apfelstrudel, Vanillesauce, Zimteis",
          price: "11",
          allergens: "Gluten, Milchprodukte, Nüsse",
          rating: 4.8,
        },
        {
          name: "Crème Brûlée",
          description: "Madagaskar-Vanilleschote, karamellisierter Zucker, saisonale Beeren",
          price: "10",
          allergens: "Eier, Milchprodukte",
          rating: 4.7,
        },
        {
          name: "Schokoladen-Fondant",
          description: "Geschmolzener dunkler Schokoladenkuchen, gesalzenes Karamell, Pistazieneis",
          price: "13",
          allergens: "Gluten, Eier, Milchprodukte, Nüsse",
          rating: 5.0,
        },
      ],
    },
  },
}
